QA-58 | Card payment UI tests
Judopay/JudoKit-Android pull request #206
Opened 2023-06-22 16:36 UTC by eugenezhernakov

Initial set of card payment tests for Android

* First time working with Espresso and Kotlin so any tips will be appreciated 💜 
* Have included `@Ignore` tests for later

2023-06-28 08:54 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        try {
Would there be a better way to do this? Works most of the time, but sometimes Global Pay requires 3 presses of the button to continue. I had a `do while` loop beforehand but that wasn't a great implementation.

2023-06-28 08:55 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +            .check(ViewAssertions.matches(ViewMatchers.hasDescendant(ViewMatchers.withText(CoreMatchers.not(receiptId)))))
I suppose this should be a boolean to assert that `receiptId` is not empty rather than a string matcher?

2023-07-03 15:56 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +    @Ignore("Skip until we can figure out how to assert PAD details are sent")
Any ideas on how I can check the PAD is being sent? This is not displayed in the result object unfortunately.

2023-07-04 14:21 UTC, RafalOzogJudopay requested changes

2023-07-04 14:21 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/ActivityResumeIdlingResource.kt
> +    override fun getName(): String = customName
It's a detail, but we don't need to declare type here, we can just use getName() = customName

2023-07-04 14:21 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +    var permissionNotifications: GrantPermissionRule = GrantPermissionRule.grant(Manifest.permission.POST_NOTIFICATIONS)
Also here we can simplify this line a bit and not to declare the type (just _permissionNotifications = ...._ )

2023-07-04 14:21 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +        onView(withText("Pay with card"))
Maybe it would be better not to access this view in this way by hard-coded string, because if the string changes in the UI, we would have to adjust all these tests relying on this hard-coded text manually one by one.

Instead, we could either access them by ID - or instead of using hard-coded string to extract it into separate variable (constant) that could be reused all over this test set.

2023-07-04 14:21 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        try {
Any kind of loop I would suggest, to avoid code redundancy.

2023-07-04 14:23 UTC, RafalOzogJudopay requested changes

2023-07-05 10:34 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        .perform(ViewActions.clearText(), ViewActions.typeText(cardSecurityCode))
What do you mean here? A separate function which takes in _where_ and _what_ to fill in on the text fields?

2023-07-05 10:35 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        try {
With the news that Global Pay are actually in the process of changing this flow/screen, let's leave this as is (as it works) just now and I'll revisit once they do their updates.

2023-07-05 12:08 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        try {
Okay

2023-07-05 12:12 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        .perform(ViewActions.clearText(), ViewActions.typeText(cardSecurityCode))
Yes, we could remove some redundancy. I would say it would be slightly cleaner, but maybe not necessary.

At the moment I don't know the Judopay codebase well yet, so I don't know how strict you guys are here about cosmetics and redundancies. So please take my comments advisory, but decide yourself whether it is worth to implement them or not (not only in this case, in general).

2023-07-05 12:19 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +            .check(ViewAssertions.matches(ViewMatchers.hasDescendant(ViewMatchers.withText(CoreMatchers.not(receiptId)))))
I am not sure if I understand your question to be honest.

As I see from this code it seems to check "whether on positions 13th in recycler view there is a a view, that contains text which is **not** equal to the receipt id.

I am happy to help with the viewmatcher selection, if you would like. Please feel free to ping me on Slack whenever, so I am happy to clarify what's expected logic for this test, and help with matcher ;)

2023-07-05 12:59 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/ActivityResumeIdlingResource.kt
> +    override fun getName(): String = customName
Done - thanks!

2023-07-05 13:00 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +        onView(withText("Pay with card"))
Done - thanks!

2023-07-05 13:22 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        .perform(ViewActions.clearText(), ViewActions.typeText(cardSecurityCode))
What do you think of this?

```
private fun fillTextField(@IdRes textFieldId: Int, text: String) {
    Espresso.onView((ViewMatchers.withId(textFieldId)))
        .perform(ViewActions.clearText(), ViewActions.typeText(text))
}
```

2023-07-05 14:03 UTC, RafalOzogJudopay commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        .perform(ViewActions.clearText(), ViewActions.typeText(cardSecurityCode))
awesome

2023-07-05 14:20 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +        .perform(ViewActions.clearText(), ViewActions.typeText(cardSecurityCode))
Pushed. Cheers for the suggestion

2023-07-06 12:23 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/Functions.kt
> +            .check(ViewAssertions.matches(ViewMatchers.hasDescendant(ViewMatchers.withText(CoreMatchers.not(receiptId)))))
As discussed, will leave as is for now.

2023-07-06 14:49 UTC, stefan-tudor commented on .circleci/config.yml
> +                - feature/QA-60-ui-tests-on-ci
@eugenezhernakov seems like you're merging this code to `master`, should it be a merge request to `feature/QA-60-ui-tests-on-ci` instead?

2023-07-06 15:00 UTC, eugenezhernakov commented on .circleci/config.yml
> +                - feature/QA-60-ui-tests-on-ci
Both going into `master`, I added some tests and changes as part of `feature/QA-60-ui-tests-on-ci` so ended up merging that branch into this one. This value you highlighted should be `master` as that's what we want the tests to run against. Need to sync them both again I suppose

2023-07-07 08:26 UTC, stefan-tudor commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +        const val CANCEL = "Cancel"
`CANCEL` is a `PaymentFeature` ? :) 

I would suggest extracting stuff like `object ValidCardDetails` `object PaymentFeatures`, in a separate test data file and simply using top-level constants instead of singletons.


ex.: 

```
TestData.kt
```

```
const val PAY_WITH_CARD_LABEL = "Pay with card"
const val CANCEL_BUTTON_TITLE = "Cancel"
```

2023-07-07 08:29 UTC, stefan-tudor commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +        Thread.sleep(500)
I'll have a look today and contribute to this PR

2023-07-07 08:38 UTC, stefan-tudor commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +    @Ignore("Skip until we can figure out how to assert PAD details are sent")
the only way is to inspect the request being sent, I'll have a think

2023-07-07 08:44 UTC, stefan-tudor commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +        Thread.sleep(1000)
why not `awaitActivityThenRun` ?

2023-07-17 15:39 UTC, eugenezhernakov commented on judokit-android-examples/src/androidTest/java/com/judokit/android/examples/test/card/CardPaymentTest.kt
> +        Thread.sleep(1000)
I don't see an obvious activity for Payment Methods in `judokit-android-examples` 🤔 Guess it'll have to be one from `com.judopay.judokit.android.ui.paymentmethods`?

2023-08-08 08:44 UTC, merged