CT-2754 | Ravelin Recommendation
Judopay/JudoKit-Android pull request #215
Opened 2023-08-21 19:48 UTC by RafalOzogJudopay

2023-08-30 13:28 UTC, stefan-tudor requested changes
Looks great overall!
Your first feature implemented at Judo 🎉 !

I dropped a few comments here and there,
I hope we manage to review this together today, I may have a few ideas on how to improve some bits.

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/api/RecommendationApiService.kt
> +    ): Call<JudoApiCallResult<RecommendationResponse>>
not sure about reusing this `JudoApiCallResult`, let's discuss this please

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/CheckCardRequest.kt
> +        fun setChallengeRequestIndicator(challengeRequestIndicator: ChallengeRequestIndicator?) =
TODO: check if this is necessary here

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PaymentRequest.kt
> +    private var scaExemption: ScaExemption?
TODO: check if this is necessary here

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthRequest.kt
> +        private var scaExemption: ScaExemption? = null
TODO: check if this is necessary here

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/TransactionOptimisation.kt
> +    val exemption: ScaExemption?,
can we reuse `ScaExemption` and `ThreeDSChallengePreference`, I think we may need a mapping logic as these may not match the recommendation server response

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/model/EncryptedCardExtension.kt
> +                keySignature = "key-signature",
these two should be provided by the Ravelin encryption lib

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/model/JudoError.kt
> +        )
let's review together this

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/model/ThreeDSChallengePreference.kt
> +}
let's check if there's any benefit in a new `enum class` only used for mapping purpose

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/RavelinCardEncryptionManager.kt
> +    @RequiresApi(22)
`RequiresApi` - is this a library requirement? we need to think what will happen with API level < 22

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/RavelinCardEncryptionManager.kt
> +        val cardDetails = CardDetails(cardNumber, expiryMonth, expiryYear, cardHolderName)
can we extract the mapping logic to a helper/extension function (maybe `CardDetails.fromTransactionDetails(details: TransactionDetails)` or something similar) so we have something like:
`fun performCardEncryption(cardDetails: CardDetails) EncryptedCard?`

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/RavelinCardEncryptionManager.kt
> +    }
These are validations and we validate the config properties in the config object `build()` method

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/RavelinCardEncryptionManager.kt
> +    fun isCardEncryptionRequired(
I would prefer this to be a separate function rather than a `..Manager`  method

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +                when (result.data?.data?.action) {
maybe we can avoid optional chaining here + remove the `null ->` case

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +    private fun areRecommendationArgumentsValid(encryptedCardDetails: EncryptedCard?, recommendationEndpointUrl: String?): Boolean {
this should be in the ravelin config object `build()` method

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +                val encryptedCardDetails = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP_MR1) {
we need to add to our feature description the SDK version limitations

2023-08-30 13:28 UTC, stefan-tudor commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +                        expirationDate!!,
🙏 let's avoid `!!` where possible

2023-09-03 20:24 UTC, RafalOzogJudopay commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
> +        val service = JudoApiServiceFactory.createJudoApiService(this, judo)
Adjusted (according to our call we're gonna have separate JudoApiServiceFactory and RecommendationApiServiceFactory - both with simple "create()" methods).

2023-09-03 21:56 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/CheckCardRequest.kt
> +        fun setChallengeRequestIndicator(challengeRequestIndicator: ChallengeRequestIndicator?) =
Hi Stefan,

I have recalled reason for this. We need the recommendation stuff (Exemption and ChallengeRequestIndicator) not only for Payment type, but also for CheckCard (this one), and PreAuth type - according to the ticket.

2023-09-03 22:02 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PaymentRequest.kt
> +    private var scaExemption: ScaExemption?
I believe we need them as both challengeRequestIndicator and scaExemption should (according to my understanding) be a part of the PaymentRequest. Before my changes we already had them in 'build' function, but they were never accessed nor used in any way.

2023-09-03 22:03 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/request/PreAuthRequest.kt
> +        private var scaExemption: ScaExemption? = null
Hi Stefan,

I have recalled reason for this. We need the recommendation stuff (Exemption and ChallengeRequestIndicator) not only for Payment type, but also for CheckCard, and PreAuth type (this one) - according to the ticket.

So I assumed i should add these two properties for CheckCard and PreAuth requests, but please correct me if I am wrong.

2023-09-04 10:11 UTC, RafalOzogJudopay commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
> +            .setIsRavelinEncryptionEnabled(isRavelinEncryptionEnabled)
Done

2023-09-04 10:12 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +    private fun areRecommendationArgumentsValid(encryptedCardDetails: EncryptedCard?, recommendationEndpointUrl: String?): Boolean {
Moved, and unnecessary checks have been removed according to our call

2023-09-04 21:49 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +                        expirationDate!!,
I agree and I am trying to avoid them as much as possible. But in this case it's Ravelin encryption function requesting these nullable values to be non-nullable before card encryption. but if you'd have idea how to improve it, please let me know

2023-09-05 08:34 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/TransactionOptimisation.kt
> +    val exemption: ScaExemption?,
Done

2023-09-05 10:18 UTC, RafalOzogJudopay commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/DemoFeatureListActivity.kt
> +        val recommendationConfiguration = if (rsaKey != null && recommendationUrl != null) {
Refactor into using sharedPref boolean

2023-09-05 10:20 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/RecommendationApiService.kt
> +    ): Call<JudoApiCallResult<RecommendationResponse>>
to be replaced potentially with Call<RecommendationRespons> - to be checked

2023-09-05 10:22 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/factory/ApiServiceFactory.kt
> +    companion object {
Refactor - do not add unnecessary stuff to Recommendation API - ssl, interceptors, gson.

2023-09-05 10:23 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/factory/ApiServiceFactory.kt
> +        add(PayLoadInterceptor(context))
for recommendation we only need NetworkConnectivityInterceptor

2023-09-05 10:24 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/factory/RecommendationApiServiceFactory.kt
> +            "http://localhost/"
extract constant

2023-09-05 10:37 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/api/model/response/TransactionOptimisation.kt
> +    val exemption: ScaExemption?,
Todo: do the same separation for ScaExemption

2023-09-05 10:40 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/model/EncryptedCardExtension.kt
> +                keySignature = "key-signature",
Todo: check with toString; if not found - take a screenshot and update story ticket with question to Ekta

2023-09-05 10:42 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/model/JudoError.kt
> +        // Todo: Ensure REQUEST_FAILED is correct Error type.
remove todo

2023-09-05 11:00 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +    private fun isCardEncryptionRequired(
Make it extension of Judo object

2023-09-05 12:33 UTC, RafalOzogJudopay commented on judokit-android/src/main/java/com/judopay/judokit/android/service/CardTransactionManager.kt
> +                val encryptedCardDetails = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP_MR1) {
I've added comment as we spoke about it (Judo class)

2023-11-30 12:48 UTC, stefan-tudor approved these changes

2023-11-30 12:50 UTC, merged