Add separate view to handle 3DS authentication
Judopay/JudoKit-Android pull request #99
Opened 2020-11-09 15:21 UTC by marcghelas

2020-11-12 15:28 UTC, stpopa requested changes
Great stuff! small things to be adjusted

2020-11-12 15:28 UTC, stpopa commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/tokenpayment/DemoTokenPaymentActivity.kt
> +                if (receipt != null) {
let's refactor this to something simpler please, something like:

```
if (receipt != null && receipt?.is3dSecureRequired) {
    
    val callback = object: ThreeDSOneCompletionCallback {
        override fun onSuccess(success: JudoPaymentResult) {
            setResult(success.code, success.toIntent())
            finish()
        }
        
        override fun onFailure(error: JudoPaymentResult) {
            setResult(error.code, error.toIntent())
            finish()
        }
    }
    
    val fragment = ThreeDSOneCardVerificationDialogFragment(service, receipt.toCardVerificationModel())
    fragment.show(supportFragmentManager, "3DS_VERIFICATION_DIALOG")
    return
}

val result = apiResult.toJudoPaymentResult(resources)
setResult(result.code, result.toIntent())
finish()
```

2020-11-12 15:28 UTC, stpopa commented on judokit-android/src/main/java/com/judokit/android/ui/cardentry/CardEntryFragment.kt
> +                ThreeDSOneCardVerificationDialogFragment(
please, let's simplify this, 
for example `CardEntryFragment : ThreeDSOneCompletionCallback` so that we will not get this callback hell here

2020-11-12 15:28 UTC, stpopa commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/tokenpayment/DemoTokenPaymentActivity.kt
> +                        ).show(supportFragmentManager, "3DS_VERIFICATION_DIALOG")
maybe we can reuse the tag defined in the SDK `THREE_DS_ONE_DIALOG_FRAGMENT_TAG`?

2020-11-12 15:28 UTC, stpopa commented on judokit-android/src/main/java/com/judokit/android/ui/paymentmethods/PaymentMethodsFragment.kt
> +                    object :
please, let's simplify this, at least let's extract the  `object : ThreeDSOneCompletionCallback` to a local variable or implement it as part of the `PaymentMethodsFragment: ThreeDSOneCompletionCallback `

2020-11-13 12:54 UTC, marcghelas commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/tokenpayment/DemoTokenPaymentActivity.kt
> +                if (receipt != null) {
Added callback as a local value

2020-11-13 12:54 UTC, marcghelas commented on judokit-android-examples/src/main/java/com/judokit/android/examples/feature/tokenpayment/DemoTokenPaymentActivity.kt
> +                        ).show(supportFragmentManager, "3DS_VERIFICATION_DIALOG")
It is public so yes we can reuse it. fixed

2020-11-13 12:55 UTC, marcghelas commented on judokit-android/src/main/java/com/judokit/android/ui/cardentry/CardEntryFragment.kt
> +                ThreeDSOneCardVerificationDialogFragment(
`CardEntryFragment` now implements `ThreeDSOneCompletionCallback` interface.

2020-11-13 12:57 UTC, marcghelas commented on judokit-android/src/main/java/com/judokit/android/ui/paymentmethods/PaymentMethodsFragment.kt
> +                    object :
Extracted the callback to local value. Didn't implement it as part of `PaymentMethodsFragment` since the callback's method signatures are generic and can't tell right away that it's 3DS related

2020-11-16 09:38 UTC, stpopa approved these changes

2020-11-16 09:45 UTC, merged